# -*- coding: utf-8 -*-
"""NN_From_From_Scratch

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/103z7qc_7rMphhLHZKXljjvNf4x9zMPvS
"""

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

data = pd.read_csv('train.csv')

data.shape

data = np.array(data)
m,n = data.shape
np.random.shuffle(data)

data_test = data[0:1000].T
y_test = data_test[0]
x_test = data_test[1:n]/255.0

data_train = data[1000 : m].T
y_train = data_train[0]
x_train = data_train[1:n]/255.0

def init_params():
  w1=np.random.rand(10, 784) * 0.01
  b1 = np.zeros((10,1))
  w2=np.random.rand(10, 10)*0.01
  b2=np.zeros((10,1))
  return w1,b1,w2,b2

def ReLU(Z):
  return np.maximum(Z,0)

def softmax(Z):
  Z -= np.max(Z,axis=0)
  A = np.exp(Z) / np.sum(np.exp(Z),axis=0)
  return A

def forward_prop(w1,b1,w2,b2,x):
  z1 = w1.dot(x) + b1
  a1 = ReLU(z1)
  z2 = w2.dot(a1)+ b2
  a2 = softmax(z2)
  return z1,a1,z2,a2

def ReLU_deriv(z):
  return z>0

def one_hot(y):
  one_hot_y = np.zeros((y.size,y.max()+1))
  one_hot_y[np.arange(y.size),y]=1
  one_hot_y = one_hot_y.T
  return one_hot_y

def backward_prop(z1,a1,z2,a2,w1,w2,x,y):
  m=x.shape[1]
  one_hot_y = one_hot(y)
  dz2 = a2-one_hot_y
  dw2 = (1/m) * dz2.dot(a1.T)
  db2 = (1/m) * np.sum(dz2)
  dz1 = w2.T.dot(dz2) * ReLU_deriv(z1)
  dw1 = (1/m) * dz1.dot(x.T)
  db1 = (1/m) * np.sum(dz1)
  return dw1,db1,dw2,db2

def update_params(w1, b1, w2, b2, dw1, db1, dw2, db2, alpha):
  w1 = w1-alpha * dw1
  b1 = b1 - alpha * db1
  w2 = w2 - alpha * dw2
  b2 = b2 - alpha * db2
  return w1,b1,w2,b2

def get_predictions(a2):
  return np.argmax(a2,axis=0)

def get_accuracy(predictions , y):
  return (np.sum(predictions == y) / y.size) * 100

def gradient_descent(x,y,alpha, iterations):
  w1,b1,w2,b2 = init_params()

  for i in range(iterations):
    z1,a1,z2,a2 = forward_prop(w1,b1,w2,b2,x)
    dw1,db1,dw2,db2 = backward_prop(z1,a1,z2,a2,w1,w2,x,y)
    w1,b1,w2,b2 = update_params(w1,b1,w2,b2,dw1,db1,dw2,db2,alpha)

    if i % 50 == 0:
      print("Iteration :",i)
      predictions = get_predictions(a2)
      print(f"Accuracy:{get_accuracy(predictions,y):.2f}%")
      print("")
  return w1,b1,w2,b2

w1,b1,w2,b2 = gradient_descent(x_train,y_train,0.1 , 501)

